version: "3.8"

services:
  fl-server:
    image: fl-server:latest
    container_name: fl-server
    restart: unless-stopped

    command: ["/bin/sh", "/opt/fl/entrypoint_fl.sh"]

    environment:
      FL_SERVER_ADDRESS: "0.0.0.0:8080"
      FL_ROUNDS: 5
      FL_MIN_CLIENTS: 2
      FL_MIN_FIT_CLIENTS: 2
      FL_MIN_EVAL_CLIENTS: 2
      SERVER_LOG_LEVEL: INFO
    networks:
      - project_default
    volumes:
      - .:/opt/fl

    ports:
      - "8080:8080"


  postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.8.0
    container_name: airflow
    depends_on:
      - postgres

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AF_USER: admin
      AF_PASS: admin

    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/opt/fl
      - ./airflow-entrypoint.sh:/airflow-entrypoint.sh

    ports:
      - "8081:8080"

    entrypoint: ["/bin/bash", "/airflow-entrypoint.sh"]

  airflow-init:
    image: apache/airflow:2.8.0
    container_name: airflow-init
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin

    user: "0:0"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
    command: db init

  airflow-webserver:
    image: apache/airflow:2.8.0
    container_name: airflow-web
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/opt/fl
    ports:
      - "8081:8080"
    command: webserver

  airflow-scheduler:
    image: apache/airflow:2.8.0
    container_name: airflow-scheduler
    depends_on:
      - airflow-init
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/opt/fl
    command: scheduler

volumes:
  postgres-db-volume:
networks:
  project_default:
    external: true
